//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopSystem.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookShopSystem.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName LastName
        ///Roger Porter
        ///Jeffrey Snyder
        ///Louis Coleman
        ///George Powell
        ///Jane Ortiz
        ///Randy Morales
        ///Lisa Davis
        ///Brenda Griffin
        ///Steven Murray
        ///Christina Jordan
        ///Paul Scott
        ///Stephen Warren
        ///Earl Bennett
        ///Rachel Hunter
        ///Lillian Robertson
        ///Randy Graham
        ///Gloria Chavez
        ///Frances Ross
        ///Jessica Bailey
        ///Julie Washington
        ///Russell Howard
        ///Chris Graham
        ///Amanda Rice
        ///Steven Owens
        ///Deborah Nichols
        ///Wanda Morales
        ///Norma Scott
        ///Amy Porter
        ///Beverly Ford
        ///Susan Castillo
        ///.
        /// </summary>
        internal static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition ReleaseDate Copies Price AgeRestriction Title
        ///1 20/01/1998 27274 15.31 2 Absalom
        ///2 5/5/1997 6713 45.78 0 A che punto Ã¨ la notte
        ///0 14/09/1998 16159 35.56 0 After Many a Summer Dies the Swan
        ///0 13/03/1999 29025 23.71 0 Ah
        ///2 12/3/1993 9998 5.26 2 Wilderness!
        ///2 22/10/2014 18832 5.69 2 Alien CornÂ (play)
        ///0 18/02/2003 28741 34.56 2 The Alien CornÂ (short story)
        ///1 11/10/1991 20471 7.18 1 All Passion Spent
        ///2 29/03/1996 9457 45.6 0 All the King&apos;s Men
        ///2 30/11/2000 17327 14.99 0 Alone on a Wide
        ///0 23 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string books {
            get {
                return ResourceManager.GetString("books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy
        ///
        ///Thriller
        ///
        ///Fiction
        ///
        ///Mystery
        ///
        ///ScienceFiction
        ///
        ///Romance
        ///
        ///Historical
        ///
        ///Crime.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
    }
}
